### ISSUE TITLE
Unable to replicate the stageB LDM finetune

### ISSUE THREAD

**Issue by HuangWanqiu** [soinx0629/vis_dec_neurips#6]
This is indeed intriguing work! 

Would it be possible for you to share the LDM pre-trained model `model.ckpt` and the associated configuration file `config.yaml` used in the `stageB_ldm_finetune`? 
Alternatively, could you kindly guide me on where I might find these files?

![image](https://github.com/soinx0629/vis_dec_neurips/assets/12394382/f1bdf74d-432c-4c34-a886-4fd699f5806c)

**Comment by Mingxiao-Li** [comment]
> This is indeed intriguing work!
> 
> Would it be possible for you to share the LDM pre-trained model `model.ckpt` and the associated configuration file `config.yaml` used in the `stageB_ldm_finetune`? Alternatively, could you kindly guide me on where I might find these files?
> 
> ![image](https://private-user-images.githubusercontent.com/12394382/298385043-f1bdf74d-432c-4c34-a886-4fd699f5806c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTg3MjEsIm5iZiI6MTcxMDE1ODQyMSwicGF0aCI6Ii8xMjM5NDM4Mi8yOTgzODUwNDMtZjFiZGY3NGQtNDMyYy00YzM0LWE4ODYtNGZkNjk5ZjU4MDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEyMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MjdhYWMyOTc0YTYzNWQzMjM4MTc0NzNiZWI5ZDYxY2RiMDk2ZWJkNTFmYzI1YzU0NzM1Y2ExMGNhMzVlZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWD2CSt1rmmEHalLQ2XROnQt3MEtVaoeaY1H24AYH4I)

Hi, we ust stable diffusion v1.4, and you can download the pretrained weights and config file from this link : https://huggingface.co/CompVis/stable-diffusion-v1-4
